---
# tasks file for ids-rule

- fail:
    msg: "Required variable 'ids_provider' is not defined"
  when: ids_provider is not defined

- fail:
    msg: "Provided value for 'ids_provider' is not valid, must be one of {{ids_provider_list}}"
  when: ids_provider not in ids_provider_list

- include_tasks: "{{ids_provider}}.yml"