---
# tasks file for ansible-role-snort

- name: install snort and dependent packages
  yum:
    name:
      - "https://www.snort.org/downloads/snort/daq-{{snort_daq_version}}-1.centos7.x86_64.rpm"
      - "https://www.snort.org/downloads/snort/snort-{{snort_version}}-1.centos7.x86_64.rpm"
      - "libdnet"
    state: installed

# This is to work around a packaing problem with upstream snort's rpm install
- name: symlink libdnet.1 to libdnet.so.1
  file:
    src: /usr/lib64/libdnet.so.1
    dest: /usr/lib64/libdnet.1
    state: link

- name: install systemd service unit file
  copy:
    src: snort.service
    dest: /etc/systemd/system/snort.service

- name: lay down sysconfig file
  template:
    src: etc_sysconfig_snort.j2
    dest: /etc/sysconfig/snort
  notify: systemctl daemon-reload

- name: get latest community rules
  get_url:
    url: "https://www.snort.org/downloads/community/community-rules.tar.gz"
    dest: "/tmp/community-rules.tar.gz"

- name: unpack snort community rules
  unarchive:
    remote_src: True
    src: "/tmp/community-rules.tar.gz"
    dest: "/etc/snort/rules"

- name: get latest registered rules
  get_url:
    url: "https://www.snort.org/rules/snortrules-snapshot-{{snort_rulesversion}}.tar.gz?oinkcode=01f5c80369e5c15d6ac49f9b284d9f4b4ddb7064"
    dest: "/tmp/snortrules-snapshot-{{snort_rulesversion}}.tar.gz"

- name: unpack snort community rules
  unarchive:
    remote_src: True
    src: "/tmp/snortrules-snapshot-{{snort_rulesversion}}.tar.gz"
    dest: "/etc/snort/rules"
